
resources:
  Resources:

    NuggetOfTheDayDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:

        AttributeDefinitions:
        - AttributeName: "nodKey"
          AttributeType: "S"

        KeySchema:
        - AttributeName: "nodKey"
          KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

        TableName: "${self:provider.environment.NUGGET_OF_THE_DAY_TABLE}"

    NuggetHistoryDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:

        AttributeDefinitions:
        - AttributeName: "nhKey"
          AttributeType: "S"

        KeySchema:
        - AttributeName: "nhKey"
          KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

        TableName: "${self:provider.environment.NUGGET_HISTORY_TABLE}"

    NuggetBaseDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:

        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "topic"
          AttributeType: "S"

        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "topic"
          KeyType: "RANGE"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

        TableName: "${self:provider.environment.NUGGET_BASE_TABLE}"

    NuggetSubscriberDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:

        AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"

        - AttributeName: "verificationStatus"
          AttributeType: "S"

        KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

        TableName: "${self:provider.environment.NUGGET_SUBSCRIBER_TABLE}"

        GlobalSecondaryIndexes:

        - IndexName: nuggetSubscriberGSI

          KeySchema:
            -
              AttributeName: verificationStatus
              KeyType: HASH

          Projection:
            NonKeyAttributes:
            -
              email

            ProjectionType: INCLUDE

          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'

    NuggeteerDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:

        AttributeDefinitions:
          -
            AttributeName: "email"
            AttributeType: "S"
          -
            AttributeName: "nuggetDeliveryFrequency"
            AttributeType: "S"

        KeySchema:
          -
            AttributeName: "email"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

        TableName: "${self:provider.environment.NUGGETEER_TABLE}"

        GlobalSecondaryIndexes:

        - IndexName: nuggetDeliveryGSI

          KeySchema:
            -
              AttributeName: nuggetDeliveryFrequency
              KeyType: HASH
            -
              AttributeName: email
              KeyType: RANGE

          Projection:
            NonKeyAttributes:
            -
              nuggetDeliveryMethod
            -
              phone

            ProjectionType: INCLUDE

          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
